config/routes.rb
require 'sidekiq/web'
require_relative '../app/api/api'
NetatlasRails::Application.routes.draw do
  devise_for :users
  mount Sidekiq::Web, at: '/sidekiq'
  mount NetAtlasAPI => '/api' 
  resources :devices do
    collection do
      get "datatable"
    end
  end
  resources :nodes do
    collection do
      get "datatable"
    end
  end
  resources :graph_items
  resources :groups do
    collection do
      get 'datatable'
      post 'add_node'
      delete 'remove_node'
    end
  end
  resources :graph_templates do
    collection do
      get 'datatable'
    end
  end
  resources :graph_template_items
  resources :pollers
  resources :outages do
    collection do
      get 'datatable'
    end
  end
  resources :data_sources do
    collection do
      get 'datatable'
    end
  end
  resources :data_templates do
    collection do
      get 'datatable'
    end
  end
  resources :interfaces do
    collection do
      get "datatable"
    end
  end
  resources :events do
    collection do
      get "datatable"
    end
  end
  resources :event_filters
  resources :notifications
  resources :contacts
  resources :services do
    collection do
      get 'datatable'
    end
  end
  resources :graphs do
    collection do
      get "datatable"
    end
    member do
      get "data"
    end
  end
  get 'map' => "map#index"
  get 'dashboard' => "dashboard#index"

  mount JasmineRails::Engine => "/specs" unless Rails.env.production?
  get "main/index"
  root :to => "dashboard#index"

end

app/models/service.rb
class Service < Node
  attr_accessible :service_type_id, :port, :device_id
  self.table_name = 'services'
  self.sequence_name = 'nodes_id_seq'
  scope :term_search, ->(term) { where("label like ?", "%#{term}%")}
  belongs_to :service_type

  def to_s; label; end
end

app/models/service_type.rb
class ServiceType < ActiveRecord::Base
  belongs_to :default_template
  attr_accessible :default_port, :description, :name
end

app/controllers/services_controller.rb
class ServicesController < NodesController
  filter_access_to :datatable, :require => :read
  self.resource_class = Service 
  self.datatable_class = ServicesDatatable
end

app/views/services/_form.html.haml
= simple_form_for @service, :html => {:class => 'form-horizontal' }  do |f|
  = f.error_notification
  .form-inputs
    = f.input :label
    = f.association :service_type
    = f.input :port
    = f.association :device, :label_field => :hostname

  .form-actions
    = f.submit nil, :class => 'btn btn-primary'

app/views/services/index.html.haml
= link_to 'Create a Service', new_service_path
%table#services{:data => {:source => datatable_services_path}}
  %thead
    %tr
      %th Name
      %th Device
      %th Actions
  %tbody

app/views/services/new.html.haml
%h1 New Service

= render 'form'

= link_to 'Back', services_path

app/views/services/show.html.haml
%table.table.table-striped.table-bordered
  %thead
    %tr
      %th{colspan: 2} Service Information
  %tbody
    %tr
      %th Name
      %td= @service.label
    %tr
      %th Device
      %td= @service.device

= render 'data_sources/list', :data_sources => @service.data_sources

= link_to 'Create Data Source', new_data_source_path(:node_id => @service.id)
= link_to 'Edit', edit_service_path(@service)
\|
= link_to 'Back', services_path