config/routes.rb
require 'sidekiq/web'
require_relative '../app/api/api'
NetatlasRails::Application.routes.draw do
  devise_for :users
  mount Sidekiq::Web, at: '/sidekiq'
  mount NetAtlasAPI => '/api' 
  resources :devices do
    collection do
      get "datatable"
    end
  end
  resources :nodes do
    collection do
      get "datatable"
    end
  end
  resources :graph_items
  resources :groups do
    collection do
      get 'datatable'
      post 'add_node'
      delete 'remove_node'
    end
  end
  resources :graph_templates do
    collection do
      get 'datatable'
    end
  end
  resources :graph_template_items
  resources :pollers
  resources :outages do
    collection do
      get 'datatable'
    end
  end
  resources :data_sources do
    collection do
      get 'datatable'
    end
  end
  resources :data_templates do
    collection do
      get 'datatable'
    end
  end
  resources :interfaces do
    collection do
      get "datatable"
    end
  end
  resources :events do
    collection do
      get "datatable"
    end
  end
  resources :event_filters
  resources :notifications
  resources :contacts
  resources :services do
    collection do
      get 'datatable'
    end
  end
  resources :graphs do
    collection do
      get "datatable"
    end
    member do
      get "data"
    end
  end
  get 'map' => "map#index"
  get 'dashboard' => "dashboard#index"

  mount JasmineRails::Engine => "/specs" unless Rails.env.production?
  get "main/index"
  root :to => "dashboard#index"

end

app/models/graph.rb
class Graph < ActiveRecord::Base
  belongs_to :graph_template
  has_many :items, :class_name => 'GraphItem'
  has_many :data_sources, :through => :items
  attr_accessible :title, :options
end

app/controllers/graphs_controller.rb
class GraphsController < ResourceController
  self.resource_class = Graph
  self.datatable_class = GraphsDatatable
  respond_to :html, :json

  def data
    start_time = params[:start] || Time.now.to_i
    end_time = params[:end] || (Time.now - 1.day).to_i
    @graph = Graph.find(params[:id])
    d = {}
    @graph.data_sources.each do |ds|
      d[ds.id] = {}
      ds.data_streams.each do |s|
        d[ds.id][s.id] = s.data(start_time, end_time).select {|s| s[1] }
      end
    end
    render :json => d
  end
end

app/views/graphs/_form.html.haml
= render :partial => 'template_item'
%div.large-6.column
  = simple_form_for(@graph) do |f|
    = f.error_notification
    .form-inputs
      = f.association :graph_template, :input_html => {:data => {'template-url' => graph_templates_path}}
      = f.input :title
      = f.input :options, :as => :text
    .form-actions
      = f.button :submit
%table#graph-items-table

%div.large-6.column
  %table
    %thead
      %tr
        %th{:colspan=> 3} Graph Items
      %tr
        %th Data Source
        %th Options
        %th
    %tbody
      - @graph.items.each do |item|
        %tr
          %td= link_to item.data_source
          %td= item.options
          %td= link_to 'Delete', item, :method => :delete
  =form_tag(graph_items_path, :method => :post) do
    %input{:type => :hidden, :name => "graph_item[graph_id]", :value => @graph.id}
    %select.expand_optgroup{:name => "graph_item[data_source_id]"}
      - Node.all.each do |n|
        %optgroup{:label => n.label}
          - n.data_sources.includes(:plugin, :node).each do |ds|
            %option{:value => ds.id}= ds.to_s
    %input{:type => :submit}

app/views/graphs/_graph.html.haml
%div
  %h2= graph.title
  %div.graph{:style => "height:300px", :data => {:id => graph.id, :options => graph.options.to_json}}

app/views/graphs/_template_item.html.erb
<script type="text/html" id="graph-item-row">
  <tr>
    <td>
      <select name="graph_item[data_source_id]">
        {{ for datasources }}
          <option value="{{id}}">{{name}}</option>
        {{/for}}
      </select>
    </td>
  </tr>
</script>

app/views/graphs/edit.html.haml
= render :partial => 'form'
= render :partial => 'graph', :locals => {:graph => @graph}

app/views/graphs/index.html.haml
%h1 Listing Graphs

%table#graphs{:data => {:source => datatable_graphs_path}}
  %thead
    %tr
      %th Title
      %th Created At
      %th Actions
  %tbody
  
%br
= link_to 'New Graph', new_graph_path, :class => "button radius"

app/views/graphs/new.html.haml
%h2 Create Graph
= render :partial => 'form'

app/views/graphs/show.html.haml
= render :partial => 'graph', :locals => {:graph => @graph}
= link_to 'Edit', edit_graph_path(@graph), :class => 'button radius'