config/routes.rb
require 'sidekiq/web'
require_relative '../app/api/api'
NetatlasRails::Application.routes.draw do
  devise_for :users
  mount Sidekiq::Web, at: '/sidekiq'
  mount NetAtlasAPI => '/api' 
  resources :devices do
    collection do
      get "datatable"
    end
  end
  resources :nodes do
    collection do
      get "datatable"
    end
  end
  resources :graph_items
  resources :groups do
    collection do
      get 'datatable'
      post 'add_node'
      delete 'remove_node'
    end
  end
  resources :graph_templates do
    collection do
      get 'datatable'
    end
  end
  resources :graph_template_items
  resources :pollers
  resources :outages do
    collection do
      get 'datatable'
    end
  end
  resources :data_sources do
    collection do
      get 'datatable'
    end
  end
  resources :data_templates do
    collection do
      get 'datatable'
    end
  end
  resources :interfaces do
    collection do
      get "datatable"
    end
  end
  resources :events do
    collection do
      get "datatable"
    end
  end
  resources :event_filters
  resources :notifications
  resources :contacts
  resources :services do
    collection do
      get 'datatable'
    end
  end
  resources :graphs do
    collection do
      get "datatable"
    end
    member do
      get "data"
    end
  end
  get 'map' => "map#index"
  get 'dashboard' => "dashboard#index"

  mount JasmineRails::Engine => "/specs" unless Rails.env.production?
  get "main/index"
  root :to => "dashboard#index"

end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :parent
  has_many :memberships
  has_many :nodes, :through => :memberships
  attr_accessible :name

  def to_s; name; end
end

app/controllers/groups_controller.rb
class GroupsController < ResourceController
  self.resource_class = Group
  self.datatable_class = GroupsDatatable

  def add_node
    @group = Group.find(params[:group_id])
    @group.nodes << Node.find(params[:node_id])
    @group.save
  end
  def remove_node
    membership = Membership.where(:node_id => params[:node_id], :group_id => params[:group_id]).first
    membership.destroy
    redirect_to :back
  end
end

app/views/groups/_form.html.haml
= simple_form_for(@group) do |f|
  = f.error_notification
  .form-inputs
    = f.input :name
  .form-actions
    = f.button :submit, :id => 'create_group'


%h2 Add Node 
%select{:id => 'add-node', :data => {'group-id' => @group.id}}
  - Node.all.each do |n|
    %option{:value => n.id}= n.label


= render 'group'

app/views/groups/_group.html.haml
%table
  %thead
    %tr
      %th Node
      %th Delete
  %tbody
    - @group.nodes.each do |node|
      %tr
        %td= link_to node, node
        %td= link_to 'Remove', remove_node_groups_path(:group_id => @group.id, :node_id => node.id), :method => :delete

app/views/groups/_list.html.haml
%table#groups{:data => {:source => datatable_groups_path}}
  %thead
    %tr
      %th Name
      %th Created At
      %th Actions
  %tbody

app/views/groups/edit.html.haml
%h1 Edit Group 

= render 'form'

= link_to 'Back', groups_path

app/views/groups/index.html.haml
%h2 Groups
= render :partial => 'list', :locals => {:groups => @groups }
%br

= link_to 'Create a Group', new_group_path, :class => "button radius"

app/views/groups/new.html.haml
%h1 New Group

= render 'form'

= link_to 'Back', groups_path

app/views/groups/show.html.haml
%h2= "Group #{@group}"
= render 'group'