config/routes.rb
require 'sidekiq/web'
require_relative '../app/api/api'
NetatlasRails::Application.routes.draw do
  devise_for :users
  mount Sidekiq::Web, at: '/sidekiq'
  mount NetAtlasAPI => '/api' 
  resources :devices do
    collection do
      get "datatable"
    end
  end
  resources :nodes do
    collection do
      get "datatable"
    end
  end
  resources :graph_items
  resources :groups do
    collection do
      get 'datatable'
      post 'add_node'
      delete 'remove_node'
    end
  end
  resources :graph_templates do
    collection do
      get 'datatable'
    end
  end
  resources :graph_template_items
  resources :pollers
  resources :outages do
    collection do
      get 'datatable'
    end
  end
  resources :data_sources do
    collection do
      get 'datatable'
    end
  end
  resources :data_templates do
    collection do
      get 'datatable'
    end
  end
  resources :interfaces do
    collection do
      get "datatable"
    end
  end
  resources :events do
    collection do
      get "datatable"
    end
  end
  resources :event_filters
  resources :notifications
  resources :contacts
  resources :services do
    collection do
      get 'datatable'
    end
  end
  resources :graphs do
    collection do
      get "datatable"
    end
    member do
      get "data"
    end
  end
  get 'map' => "map#index"
  get 'dashboard' => "dashboard#index"

  mount JasmineRails::Engine => "/specs" unless Rails.env.production?
  get "main/index"
  root :to => "dashboard#index"

end

app/models/data_template.rb
class DataTemplate < ActiveRecord::Base
  belongs_to :plugin
  attr_accessible :arguments, :critical_threshold, :description, :interval, :name, :operator, :warning_threshold, :plugin_id, :node_type
  def to_s; name; end
end

app/controllers/data_templates_controller.rb
class DataTemplatesController < ResourceController
  self.resource_class = DataTemplate
  self.datatable_class = DataTemplatesDatatable
end

app/views/data_templates/_form.html.haml
= simple_form_for(@data_template, :html => {:class => 'form-horizontal'}) do |f|
  = f.error_messages
  .form-inputs
    = f.input :name
    = f.association :plugin
    = f.input :node_type, :as => :select, :options => ['Device', 'Interface', 'Service']
    = f.input :interval
    = f.input :warning_threshold
    = f.input :critical_threshold
    = f.input :operator, :as => :select, :collection => ['>','<']
    = f.input :arguments, :as => :text

  .form-actions
    = f.button :submit, :id => 'create_data_template'

app/views/data_templates/edit.html.haml
%h1 Edit Data Template

= render 'form'
= link_to 'Back', data_templates_path

app/views/data_templates/index.html.haml
%table#data_templates{:data => {:source => datatable_data_templates_path}}
  %thead
    %th Name
    %th Plugin
    %th Actions
  %tbody
%br
= link_to 'Create a Data Template', new_data_template_path, :class => "button radius"

app/views/data_templates/new.html.haml
%h1 New Data Template

= render 'form'
= link_to 'Back', data_templates_path

app/views/data_templates/show.html.haml
%h3 Data Template
%table
  %tr
    %th Name
    %td= @data_template.name
  %tr
    %th Plugin
    %td= @data_template.plugin
  %tr
    %th Node Type
    %td= @data_template.node_type
  %tr
    %th Interval
    %td= @data_template.interval
  %tr
    %th Warning Threshold
    %td= @data_template.warning_threshold
  %tr
    %th Critical Threshold
    %td= @data_template.critical_threshold
  %tr
    %th Operator
    %td= @data_template.operator
  %tr
    %th Description
    %td= @data_template.description
  %tr
    %th Arguments
    %td= @data_template.arguments.to_json

=link_to 'Edit', edit_data_template_path(@data_template)